# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Central Utah Linux/Unix User Group
email: contact@culug.group
description: >- # this means to ignore newlines until "baseurl:"
  Central Utah Linux/Unix User Group (CULUG) is a technology-focused user group supporting Linux, Unix (i.e. MacOS) or Unix-like technologies.
  The group is intended to serve as a casual meeting space for people interested in technology in the Central Utah area.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://culug.group" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username: central-utah-lug

# Build settings
markdown: kramdown
theme: jekyll-remote-theme 
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag 

plausible_analytics: culug.group
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Custom stuff
navigation_header:
- title: home
  url: /
- title: about 
  url: /about/
- title: venue 
  url: /venue/
- title: contact 
  url: /contact/

navigation_footer:
- title: home
  url: /
- title: about 
  url: /about/
- title: venue 
  url: /venue/
- title: contact 
  url: /contact/

feature_image: _images/culug.png
